version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 147397011329.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t wordpress .
      - docker tag wordpress:latest 147397011329.dkr.ecr.us-east-1.amazonaws.com/wordpress:latest
      - echo Creating imagedefinitions.json...
      - echo '[{"name":"wordpress","imageUri":"147397011329.dkr.ecr.us-east-1.amazonaws.com/wordpress:latest"}]' > imagedefinitions.json
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 147397011329.dkr.ecr.us-east-1.amazonaws.com/wordpress:latest

artifacts:
  files:
    - imagedefinitions.json
