version: 0.2
phases:
  build:
    commands:
      - docker build -t wordpress .
      - $(aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 147397011329.dkr.ecr.region.amazonaws.com)
      - docker tag wordpress:latest 147397011329.dkr.ecr.us-east-1.amazonaws.com/wordpress:latest
      - docker push 147397011329.dkr.ecr.us-east-1.amazonaws.com/wordpress:latest
