version: 0.2

phases:
  install:
    commands:
      - echo Installing Docker...
      - apt-get update
      - apt-get install -y docker.io
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 147397011329.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t wordpress .
      - docker tag wordpress:latest 147397011329.dkr.ecr.us-east-1.amazonaws.com/wordpress:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 147397011329.dkr.ecr.us-east-1.amazonaws.com/wordpress:latest

artifacts:
  files:
    - '**/*'
